### ISSUE TITLE
Error: redirection is not supported

### ISSUE THREAD

**Issue by gvwilson** [swcarpentry/windows-installer#50]
Reported by someone setting up for a workshop this weekend:
- My installation did not go perfectly. I installed Git Bash and the Software Carpentry Windows installer. Git Bash installed correctly:
  ![image003](https://cloud.githubusercontent.com/assets/911566/15914224/0c41a702-2dad-11e6-8f4f-31bb2a876c2a.png)
- Software Carpentry did not:
  ![image004](https://cloud.githubusercontent.com/assets/911566/15914229/162be3ea-2dad-11e6-973f-58cd378dab24.png)

Any suggestions?

**Comment by ethanwhite** [comment]
They probably didn't follow the installation instructions for GitBash properly. This sounds like the #31 issue.

**Comment by gvwilson** [comment]
From #31: Have the students reinstall Git for Windows to use the Windows console. They would need to make a change on the 5th page of the installer wizard.

**Comment by ctmontgomery** [comment]
That worked! Thank you!

**Comment by embray** [comment]
So wait, does the version of nano we're installing not work with mintty?

**Comment by iamc** [comment]
Is nano the only key software affected by this issue?

If so, this is trivially fixed for mintty adding 
```
alias nano='winpty nano'
```
in `.bash_profile` through the installer.

I'm just about doing this for our incoming  workshop as we will only use bash, git, ipython and ...nano!

This will make the "Git for Windows" installation a completely default one.

**Comment by ethanwhite** [comment]
> alias nano='winpty nano'

We had a report in the original issue that this wasn't working because it resulted in not being able to move the cursor around:
https://github.com/swcarpentry/windows-installer/issues/31#issuecomment-133718108

Maybe this has been fixed?

**Comment by iamc** [comment]
> ```
> alias nano='winpty nano'
> ```
> We had a report in the original issue that this wasn't working because it resulted in not being able to move the cursor around:
> #31 (comment)

No, you're completely right, it's not fixed. Thanks for the heads up!
